Repository foremast/foremast, pull requests merged in 2020-10, with the labels that each got.

#433 fix: Docs issue with CloudFunction timeouts
  _docs/configuration_files/application_json.rst
Labels: hacktoberfest

#436 fix: better error message when cloud function event resource has duplicate project id
  src/foremast/cloudfunction/cloud_functions_client.py
Labels: bug

#437 fix: Added Missing Licenses on contributions
  src/foremast/gcp_iam/create_iam_resources.py
  src/foremast/utils/google_iap.py
Labels: documentation, hacktoberfest, style
